- name: Create DB
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    name: "{{ db_name }}"
    state: "present"
  delegate_to: "{{ groups.frontend.0 }}"
  tags:
    - create-db

- name: Create DB user
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ db_username }}.*:ALL"
  with_items:
    - "localhost"
    - "%"
  delegate_to: "{{ groups.frontend.0 }}"
